### ISSUE TITLE
Cannot setup local dev environment.

### ISSUE THREAD

**Issue by prlyons** [Gig-o-Matic/GO3#239]
New to python and not sure what the issue is other than it's having trouble with psycopg. I wanted to test a change to the calendar strings.

I'm at this point in the local development setup:

> pip3 install -r requirements.txt
> pip3 install -r requirements.postgres.txt
> python3 manage.py migrate
> 

And I get the following error:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg as Database
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/psycopg/__init__.py", line 9, in <module>
    from . import pq  # noqa: F401 import early to stabilize side effects
    ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/psycopg/pq/__init__.py", line 114, in <module>
    import_from_libpq()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/psycopg/pq/__init__.py", line 106, in import_from_libpq
    raise ImportError(
ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: libpq library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 27, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/patricklyons/Documents/gigo3/GO3/manage.py", line 21, in <module>
    main()
  File "/Users/patricklyons/Documents/gigo3/GO3/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/patricklyons/Documents/gigo3/GO3/member/models.py", line 18, in <module>
    from django.contrib.auth.models import AbstractUser, BaseUserManager
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/contrib/auth/base_user.py", line 57, in <module>
    class AbstractBaseUser(models.Model):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/models/base.py", line 143, in __new__
    new_class.add_to_class("_meta", Options(meta, app_label))
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/models/base.py", line 371, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/models/options.py", line 243, in contribute_to_class
    self.db_table, connection.ops.max_name_length()
                   ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/utils.py", line 193, in create_connection
    backend = load_backend(db["ENGINE"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/utils.py", line 113, in load_backend
    return import_module("%s.base" % backend_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 or psycopg module")
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 or psycopg module

**Comment by prlyons** [comment]
Googling suggested using [these steps](https://pypi.org/project/psycopg/) to install psycopg.

> pip install --upgrade pip           # to upgrade pip
> pip install "psycopg[binary,pool]"  # to install package and dependencies

The new error message is:
patricklyons@Patricks-MacBook-Air GO3 % python3 manage.py migrate
Traceback (most recent call last):
  File "/Users/patricklyons/Documents/gigo3/GO3/manage.py", line 21, in <module>
    main()
  File "/Users/patricklyons/Documents/gigo3/GO3/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/patricklyons/Documents/gigo3/GO3/member/models.py", line 29, in <module>
    from lib.email import EmailRecipient
  File "/Users/patricklyons/Documents/gigo3/GO3/lib/email.py", line 7, in <module>
    from markdown import markdown
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/markdown/__init__.py", line 29, in <module>
    from .core import Markdown, markdown, markdownFromFile  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/markdown/core.py", line 26, in <module>
    from . import util
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/markdown/util.py", line 87, in <module>
    INSTALLED_EXTENSIONS = metadata.entry_points().get('markdown.extensions', ())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'
patricklyons@Patricks-MacBook-Air GO3 %

**Comment by bklang** [comment]
Hey, sorry you ran into this. It looks like the DB client library, psycopg, needs an underlying implementation as a dependency, and users have their choice of at least 3 options.  Try doing this locally to get up and running:

`pip install psycopg_binary`

I'll use this issue to look into a permanent solution that I can build into the requirements.postgres.txt

**Comment by bklang** [comment]
@prlyons I've updated the getting started docs. Take a look at #247 and see if that helps?

**Comment by prlyons** [comment]
Thanks! I’ll let you know how it goes.

**Comment by prlyons** [comment]
I followed the new steps and still get this error running migrate. I do see the docker container for the db running. The error below appears to be an issue importing some libraries.

patricklyons@Patricks-MacBook-Air GO3 % python3 manage.py migrate
Traceback (most recent call last):
  File "/Users/patricklyons/Documents/gigo3/GO3/manage.py", line 21, in <module>
    main()
  File "/Users/patricklyons/Documents/gigo3/GO3/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/patricklyons/Documents/gigo3/GO3/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/patricklyons/Documents/gigo3/GO3/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/Users/patricklyons/Documents/gigo3/GO3/.venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/patricklyons/Documents/gigo3/GO3/.venv/lib/python3.12/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/Users/patricklyons/Documents/gigo3/GO3/.venv/lib/python3.12/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/patricklyons/Documents/gigo3/GO3/member/models.py", line 29, in <module>
    from lib.email import EmailRecipient
  File "/Users/patricklyons/Documents/gigo3/GO3/lib/email.py", line 7, in <module>
    from markdown import markdown
  File "/Users/patricklyons/Documents/gigo3/GO3/.venv/lib/python3.12/site-packages/markdown/__init__.py", line 29, in <module>
    from .core import Markdown, markdown, markdownFromFile  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patricklyons/Documents/gigo3/GO3/.venv/lib/python3.12/site-packages/markdown/core.py", line 26, in <module>
    from . import util
  File "/Users/patricklyons/Documents/gigo3/GO3/.venv/lib/python3.12/site-packages/markdown/util.py", line 87, in <module>
    INSTALLED_EXTENSIONS = metadata.entry_points().get('markdown.extensions', ())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'

**Comment by prlyons** [comment]
The DB container is running.
% pg_isready --host=127.0.0.1 --username=test --port=15432
127.0.0.1:15432 - accepting connections

**Comment by bklang** [comment]
It looks like this is a problem with Python 3.12. I'm still trying to work out exactly what the problem is, but it looks like Python 3.12 includes a version of `importlib-metadata` which is too new for the version of `markdown`. I'm looking to see if I can upgrade `markdown` to be compatible.

**Comment by bklang** [comment]
I've tested with Python 3.9 and 3.11 successfully

**Comment by prlyons** [comment]
OK I can move to an earlier version.

**Comment by bklang** [comment]
Hold on before you do, I'm testing the newer version of the Markdown library. The server is booting under Python 3.12 now

**Comment by prlyons** [comment]
OK. Thanks for all the help!

**Comment by prlyons** [comment]
OK I've got a local server running!  
For some reason it reported that it couldn't find .env using the symlink "ln -s go3/.env.example go3/.env" so I remove it and created the file from the example file.

**Comment by bklang** [comment]
Great! So glad to hear it! Thanks for sticking through the process.

I'm merging #247, so don't forget to switch back to the `main` branch.
